name: Build, Release, and Install
on:
  release:
    types:
      - prereleased
jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      sha: ${{ steps.tag.outputs.sha }}
    steps:
      - id: tag
        run: |
          SHORT_SHA=$(echo "$SHA" | sed 's/\(.\{8\}\).*/\1/')
          echo "$SHORT_SHA ($SHA)"
          echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          echo "sha=$SHORT_SHA" >> $GITHUB_OUTPUT
        env:
          SHA: ${{ github.sha }}
  build:
    uses: ./.github/workflows/build.yaml
    needs: [tag]
    permissions:
      pages: write
      contents: write
      id-token: write
    with:
      prerelease: true
      tag: ${{ needs.tag.outputs.tag }}
      deployment: "PROD-${{ github.actor }}-${{ needs.tag.outputs.sha }}"
  install:
    uses: ./.github/workflows/install.yaml
    needs: [tag, build]
    permissions:
      contents: write
    with:
      deployment: "PROD-${{ github.actor }}-${{ needs.tag.outputs.sha }}"
      tag: ${{ needs.tag.outputs.tag }}
      url: ${{ needs.build.outputs.url }}
    concurrency:
      group: PRODUCTION-LOGIN
      cancel-in-progress: true
