name: Update Token
on:
  schedule:
    - cron: 3 12-22/5 * * *
    - cron: 53 12-22/5 * * *
    - cron: 43 13-23/5 * * *
    - cron: 33 14-19/5 * * *
    - cron: 23 15-20/5 * * *
    - cron: 13 16-21/5 * * *
    - cron: 33 0 * * *
    - cron: 23 1 * * *
  workflow_dispatch: null
env:
  REMOTE: '${{ github.repository }}'
  ROOT: 'https://api.github.com'
  API: 'X-GitHub-Api-Version: 2022-11-28'
  OCTET: 'Accept: application/octet-stream'
  VND: 'Accept: application/vnd.github+json'
  AUTH: 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
concurrency:
  group: PRODUCTION-LOGIN
  cancel-in-progress: false
permissions:
  contents: write
  pages: read
jobs:
  read_env:
    uses: ./.github/workflows/read_env.yaml
    permissions:
      pages: read
  reset_token:
    needs: [read_env]
    environment:
      name: ${{ needs.read_env.outputs.deployment }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure Latest Release URL
        id: index
        run: |
          JSON=$(curl -s \
            -H "$API" -H "$AUTH" -H "$VND"\
            $ROOT/repos/$REMOTE/releases/latest)
          BODY=$(jq -r '.body' <<< $JSON)
          ID=$(jq -r '.id' <<< $JSON)
          PUB=$(echo "$BODY" | head -n1)
          URL=$(jq -r '.assets[0].url' <<< $JSON)
          echo "index=$URL" >> $GITHUB_OUTPUT
          echo "release=$ID" >> $GITHUB_OUTPUT
          echo "pub=$PUB" >> $GITHUB_OUTPUT
      - name: Login Open
        run: |
          curl --location-trusted \
            -H "$API" -H "$AUTH" -H "$OCTET"\
            -o index "$INDEX_URL"
          chmod +x index
          echo "" > secret.txt
          ./index UPDATE TOKEN "$PUB"
          STEP=$(head -n 1 secret.txt)
          MESSAGE="Use your private login link."
          ./index SHARE "$GITHUB_TOKEN" "$RELEASE" "$STEP" "$MESSAGE"
        env:
          DEPLOYMENT: ${{ needs.read_env.outputs.deployment }}
          PUB: '${{ steps.index.outputs.pub }}'
          ROOT__INSTALLATION: '${{ secrets.ROOT__INSTALLATION }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          INDEX_URL: '${{ steps.index.outputs.index }}'
          RELEASE: '${{ steps.index.outputs.release }}'
